
name: flutter_map_training
description: Flutter application with google maps support for mobile and web platforms

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

  firebase_core: ^2.3.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.1.5
  flutter_secure_storage: ^9.0.0
  logging: ^1.1.0

  #state
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  #network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0

  #maps
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.5.4+3
  google_maps_cluster_manager: ^3.0.0+1
  geolocator: ^10.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/map_type_normal.png
    - assets/images/map_type_satellite.png
    - assets/icons/google_logo.svg